proxy: http://xray.lan:1081
proxy_after: 3
dir_repos: repos
dir_archives: archives
dir_checkouts: checkouts
repos:
  - https://github.com/7Ji/orangepi5-archlinuxarm.git:
      wanted:
        - 2c59c1ce5145680a31052e8fc1b3b3bd170b1ec4
  - https://github.com/7Ji/ampart.git:
      wanted:
        - HEAD
        - v1.3:
            type: tag
        - master
        - MASTER
        - v1.2
    
        # - fcd1b77155e2bb06d4b6ae8ceb83a694d958f6c2
        # - master
            # archive: yes
        # - v1.0.3:
        #     type: tag
#   - git://git.lan/YAopenvfD.git
  # what: